# Created using wingetcreate 0.3.0.3
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Fortinet.FortiClientVPN
PackageVersion: 7.0.1.0083
InstallerSwitches:
  Silent: /QUIET /NORESTART
  SilentWithProgress: /PASSIVE /NORESTART
Installers:
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://filestore.fortinet.com/forticlient/downloads/FortiClientVPNOnlineInstaller_7.0.exe
  InstallerSha256: D9879EC8B0EB1FC3D47C2476198CEE8C9B56CA733E89634F6FE13B405508A6F5
ManifestType: installer
ManifestVersion: 1.0.0
